Make BoringSSL wrapper match CryptoKit behaviour when working with x9.63
apple/swift-crypto pull request #128
Opened 2022-08-22 15:53 UTC by wrinkl3

…63 representation

Make BoringSSL wrapper match CryptoKit behaviour when working with x9.63

### Checklist
- [x] I've run tests to see all new and existing tests pass
- [x] I've followed the code style of the rest of the project
- [x] I've read the [Contribution Guidelines](CONTRIBUTING.md)
- [x] I've updated the documentation if necessary

### Motivation:

Recent versions of CryptoKit have changed how key initialization for EC x9.63 representation works. `P256.KeyAgreement.PublicKey(compressedRepresentation: Bytes)` now only accepts uncompressed form, while `P256.KeyAgreement.PublicKey(x963Representation: Bytes)` only accepts the compressed form. We'd like to bring that behavior in line with our BoringSSL wrappers.

### Modifications:

* Modified the `x963Representation `/`compressedRepresentation ` wrappers to only accept compressed/uncompressed key length size
* Modified the unit tests to call `compressedRepresentation` when passing in compressed representation keys

### Result:

The BoringSSL wrapper behaviour now matches CryptoKit, and the unit tests now work with CryptoKit's latest version.

2022-08-22 18:00 UTC, FredericJacobs commented
Seems reasonable to me. @Lukasa ?

2022-08-23 05:58 UTC, Lukasa requested changes
Thanks for this @wrinkl3, this looks great! Can I ask you to add some checks to `testCompressedKeys` to confirm that the `PublicKey.init(x963Representation:)` initialisers fail with compressed keys? I'd also love another test that is essentially the "other way", showing that `PublicKey.x963Representation` cannot be passed to `PublicKey.init(compressedRepresentation:)`.

Otherwise this looks great!

2022-08-23 05:58 UTC, Lukasa commented
@swift-server-bot add to allowlist

2022-08-23 10:47 UTC, Lukasa approved these changes
Nice one, thanks!

2022-08-23 10:47 UTC, merged