Make NIST `PublicKey`s conform to `Hashable`
apple/swift-crypto pull request #176
Opened 2023-04-18 10:51 UTC by Sajjon

Make ALL `NIST` PublicKeys conform to `Hashable`

N.B. Merge open PR #174 first (or if #174 is closed, close this one too), since this PR builds on top of that.

### Checklist
- [X] I've run tests to see all new and existing tests pass
- [X] I've followed the code style of the rest of the project
- [X] I've read the [Contribution Guidelines](CONTRIBUTING.md)
- [X] I've updated the documentation if necessary

#### If you've made changes to `gyb` files
- [x] I've run `.script/generate_boilerplate_files_with_gyb` and included updated generated files in a commit of this pull request

### Motivation:

This is the `NIST` analogue counterpart of #175, so the motivation put in there applies here as well.

This PR is an addition of open PR #174. 

### Modifications:

1. Make `P256`, `P384` and `P521`'s _Signing_ and _KeyAgreement_ `PublicKey` be `Hashable`, by...
2. ... marking `NISTECPublicKey` to be `Hashable` and adding `hash:into` function in `ECDH.swift.gyb`
3. Add tests for these. 

### Result:

ALL NIST PublicKey's now conform to `Hashable`

2023-04-18 10:55 UTC, Sajjon commented on Sources/Crypto/Key Agreement/ECDH.swift
> +			public static func ==(lhs: Self, rhs: Self) -> Bool {
Equatable, Part of #174 but I was unable to create a diff between just this PR and the source branch of that PR.

2023-04-18 10:55 UTC, Sajjon commented on Sources/Crypto/Key Agreement/ECDH.swift.gyb
> +			public static func ==(lhs: Self, rhs: Self) -> Bool {
Equatable, Part of #174 but I was unable to create a diff between just this PR and the source branch of that PR.

2023-04-18 10:55 UTC, Sajjon commented on Tests/CryptoTests/Signatures/ECDSA/ECDSASignatureTests.swift
> +	func testP256SigningPublicKeyEquatable() throws {
Equatable, Part of #174 but I was unable to create a diff between just this PR and the source branch of that PR.

2023-04-19 05:57 UTC, Lukasa requested changes
Blocking for future CryptoKit updates.

2024-09-09 15:36 UTC, Sajjon commented
@Lukasa Context:

I informed lots of repos that Github user "vivoxfold3" had suspicous activity:
1. has no sources (only forks)
2. no profile photo
3. no followers
4. no bio
5. forks ~10 crypto libs or repos used by crypto libs / wallets all *within the same hour*
6. makes trivial contributions and **tries to "falsify" a GPG signature** by writing "Signed off by"
7. ignores PR templates

The **exact same behaviour** was done by GH use `vivoxfold3` also last week, which responded using... hmm... interesting phrasing:

https://github.com/hoprnet/hoprnet/pull/6482#issuecomment-2333638612

> "Unreasonable accusations from persecuted delusional patients"

Whatever that means? Obvious bad translation service.

==================

The difference between you vivoxfold3 and me is that I:
1. Have many of SOURCE repos (not forks) with many stars
2. My Github User is over 10 years old
3. I have profile photo
4. I have 100 followers
5. I have a bio
6. I have many verified email addresses
7. I'm a Github PRO user
8. I do in fact work in the crypto industry, unlike you doing trivial PRs intro 10 different crypto libs...
9. My contributions fixing typos are non-trivial - often spent 1-3 hours per

2024-09-09 15:55 UTC, Lukasa commented
Thanks for the input here @Sajjon. I'm going to hide both comments, and report @vivoxfold3's, as the assertion is transparently untrue (this is not your first contribution here, and you and I have spoken several times before. The hide is only to keep this PR on-topic, not because your comment wasn't welcome.

2025-03-17 12:23 UTC, closed without merging