Switch to canImport instead of os conditions
apple/swift-crypto pull request #184
Opened 2023-06-22 17:43 UTC by FranzBusch

2023-06-26 16:55 UTC, tomerd approved these changes

2023-07-09 12:04 UTC, Lukasa commented
@FranzBusch Can you fix up the soundness stuff here?

2023-07-09 12:05 UTC, Lukasa requested changes

2023-07-09 12:05 UTC, Lukasa commented on Sources/Crypto/AEADs/AES/GCM/AES-GCM.swift
> +#if canImport(CryptoKit) && !CRYPTO_IN_SWIFTPM_FORCE_BUILD_API
This is wrong: these files are used to _build_ `CryptoKit`, so this branch can't safely rely on the `canImport` here. Prefer `canImport(Darwin)`.

2023-07-20 09:22 UTC, Lukasa approved these changes
This LGTM.

2023-07-20 09:47 UTC, Lukasa commented
Can you clean up the soundness and cmake things?

2023-07-20 21:31 UTC, merged