Add extern C markers
apple/swift-crypto pull request #204
Opened 2023-10-17 23:31 UTC by brianmichel

Ensure C linkage for shims to allow for usage in C++ interop environments.

### Checklist
- [x] I've run tests to see all new and existing tests pass
- [x] I've followed the code style of the rest of the project
- [x] I've read the [Contribution Guidelines](CONTRIBUTING.md)
- [x] I've updated the documentation if necessary

#### If you've made changes to `gyb` files
- [ ] I've run `.script/generate_boilerplate_files_with_gyb` and included updated generated files in a commit of this pull request

### Motivation:

This library when consumed from a swift package that has C++ interop enabled fails to successfully link since the symbols seem to get mangled.

### Modifications:

I've added conditional `extern "C"` markers in the shims file if and only iff C++ is detected.

### Result:

You should be able to consume and link this library in a target that has C++ interop enabled.

2023-10-17 23:48 UTC, compnerd requested changes
I feel uneasy about this.  This only impacts the implementation and not the declaration which are consumed by the ClangImporter and thus this can lead to a mismatch in the linkage.

2023-10-18 01:29 UTC, brianmichel commented
> I feel uneasy about this. This only impacts the implementation and not the declaration which are consumed by the ClangImporter and thus this can lead to a mismatch in the linkage.

Ah this should likely just be in the header files, right? Sorry, long day of debugging.

2023-10-18 01:50 UTC, compnerd reviewed
@swift-server-bot please test

2023-10-18 08:21 UTC, Lukasa commented
@swift-server-bot test this please

2023-10-18 08:21 UTC, Lukasa approved these changes

2023-10-19 19:38 UTC, compnerd commented
@Lukasa can we get this merged please?

2023-10-20 07:05 UTC, merged