Add support for pkcs1 oaep sha256
apple/swift-crypto pull request #206
Opened 2023-10-19 16:21 UTC by rnro

‼️ To be merged after https://github.com/apple/swift-crypto/pull/205

Add support for pkcs1 oaep sha256

### Motivation

Add RSA OAEP-sha256 support in addition to the increasingly aged SHA-1
implementation.

### Modifications

* Add a `Digest` enum to `_RSA.Encryption.Padding`
* Add a digest associated type to the `.pkcs1_oaep` padding enum case
  to allow us to distinguish different digest hash functions.
* Add a `PKCS1_OAEP_SHA256` public static let to allow users to use the
  new hash function.
* Enable SHA-256 RSA encryption tests

### Result

* Support for RSA OAEP-sha256

**NOTE:** This change sticks with the BoringSSL default behaviour and the case which uses the new SHA-256 digest hash function also uses SHA-256 as its mask generation function.

2023-10-30 11:43 UTC, Lukasa requested changes
I've left some notes, please also update RSA_security.swift.

2023-10-30 11:43 UTC, Lukasa commented on Sources/_CryptoExtras/RSA/RSA.swift
> +        case blake2b256
This is excessive, let's just have only the digests we actually support.

2023-10-30 11:43 UTC, Lukasa commented on Tests/_CryptoExtrasTests/TestRSAEncryption.swift
> +        let padding: _RSA.Encryption.Padding
We should add a new set of test vectors: https://github.com/google/wycheproof/blob/master/testvectors/rsa_oaep_2048_sha256_mgf1sha256_test.json

2023-10-31 18:37 UTC, Lukasa approved these changes

2023-10-31 18:38 UTC, Lukasa requested changes
Sorry, hang-on: we need a Security.framework equivalent.

2023-11-01 11:23 UTC, dnadoba approved these changes

2023-11-06 11:25 UTC, Lukasa approved these changes
Nice one @rnro, thanks!

2023-11-06 11:25 UTC, merged